[package]
name = "rfuses_device_local"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
log.workspace = true
fuser.workspace = true
rfuse_core = { path = "../../crates/rfuse_core" }
rfuse_device_disk = { path = "../../crates/rfuse_device_disk", features = ["local"]}
walkdir.workspace = true
nix.workspace = true
fern.workspace = true
ctrlc.workspace = true
clap.workspace = true
colored.workspace = true
chrono.workspace = true

[target.'cfg(debug_assertions)'.dependencies]
env_logger.workspace = true
