name: codspeed-benchmarks

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
  merge_group:
  workflow_dispatch:


jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install package
        run: |
            sudo apt-get update
            sudo apt-get install fuse3 libfuse3-dev

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      # - name: run benchmark
      #   run: cargo bench

      - name: Build the benchmark target(s)
        run: cargo codspeed build

      # 会有权限错误，暂不清楚
      - name: Run the benchmarks
        uses: CathalMullan/action@main
        env:
          RUST_BACKTRACE: full
        with:
          shell: /bin/bash sudo
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
