name: codspeed-benchmarks

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
  merge_group:
  workflow_dispatch:


jobs:
  benchmarks:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --security-opt=seccomp=unconfined --privileged=true --device=/dev/fuse
    steps:
      - uses: actions/checkout@v4

      - name: install package
        run: |
          apt-get update
          apt-get install fuse3 libfuse3-dev libfuse-dev pkg-config libssl-dev gcc g++ curl wget build-essential lsb-release git -y
          echo "user_allow_other" >> /etc/fuse.conf
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: link project
        run: |
          mkdir -p /home/runner/work/rfuse
          ln -s /__w/rfuse/rfuse/ /home/runner/work/rfuse/rfuse

      - name: init git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global --add safe.directory "*"

      # - name: Setup rust toolchain, cache and cargo-codspeed binary
      #   uses: moonrepo/setup-rust@v1
      #   with:
      #     channel: stable
      #     cache-target: release
      #     bins: cargo-codspeed

      - name: install cargo-codspeed
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/CodSpeedHQ/runner/releases/download/v3.0.0/codspeed-runner-installer.sh | sh

      # - name: run benchmark
      #   run: cargo bench

      # 会有权限错误，暂不清楚
      - name: Build the benchmark target(s)
        run: cargo codspeed build

      # - name: Run the benchmarks
      #   uses: CodSpeedHQ/action@v3
      #   with:
      #     run: cargo codspeed run
      #     token: ${{ secrets.CODSPEED_TOKEN }}

      - name: Run the benchmarks
        run: codspeed run --token ${{ secrets.CODSPEED_TOKEN }} cargo codspeed run
