name: codspeed-benchmarks

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
  merge_group:
  workflow_dispatch:


jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install package
        run: |
            sudo apt-get update
            sudo apt-get install fuse3 libfuse3-dev

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        env:
          RUST_BACKTRACE: 1
        with:
          run: sudo cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
