name: Build

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
  merge_group:
  workflow_dispatch:


jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        target: [x86_64, aarch64]
        build_type: [debug, release]
    name: Ubuntu, ${{ matrix.target }}. ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v4
      - name: update cargo to 1.80.0
        run: rustup update
      - name: Install aarch64 target
        if: matrix.target == 'aarch64'
        run: rustup target add ${{ matrix.target }}-unknown-linux-gnu
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
            targets: ${{ matrix.target }}-unknown-linux-gnu
            toolchain: stable
            components: rust-src
      - uses: actions/cache@v4
        id: cargo-cache
        with:
            path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
                target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install package
        if: matrix.target == 'aarch64'
        run: |
            sudo dpkg --add-architecture ${{ matrix.target }}
            sudo apt-get update
            sudo apt-get install fuse3:${{ matrix.target }} libfuse3-dev:${{ matrix.target }}
      - name: install package
        if: matrix.target == 'x86_64'
        run: |
            sudo apt-get update
            sudo apt-get install fuse3 libfuse3-dev
      - name: Build
        if: matrix.build_type == 'release'
        run: cargo build --target ${{ matrix.target }}-unknown-linux-gnu --${{ matrix.build_type }}
      - name: Build
        if: matrix.build_type == 'debug'
        run: cargo build --target ${{ matrix.target }}-unknown-linux-gnu

#   macos:
#     strategy:
#         matrix:
#             target: [x86_64, aarch64]
#             build_type: [debug, release]
#     runs-on: macos-latest
#     name: Macos, ${{ matrix.target }}
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/cache@v4
#         id: cargo-cache
#         with:
#             path: |
#                 ~/.cargo/bin/
#                 ~/.cargo/registry/index/
#                 ~/.cargo/registry/cache/
#                 ~/.cargo/git/db/
#                 target/
#             key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#       - name: Build
#         if: matrix.build_type == 'release'
#         run: cargo build --target ${{ matrix.target }}-apple-darwin --${{ matrix.build_type }}
#       - name: Build
#         if: matrix.build_type == 'debug'
#         run: cargo build --target ${{ matrix.target }}-apple-darwin