on:
    push:
      branches: [master]
      tags: ["v*"]
    pull_request:
    merge_group:
    workflow_dispatch:

name: Test coverage

jobs:
    coverage:
        name: Collect test coverage
        runs-on: ubuntu-latest
        # nightly rust might break from time to time
        continue-on-error: true
        env:
            RUSTFLAGS: -D warnings
            CARGO_TERM_COLOR: always
        steps:
          - uses: actions/checkout@v4 # v4
            # Nightly Rust is used for cargo llvm-cov --doc below.
          - uses: dtolnay/rust-toolchain@nightly
            with:
              components: llvm-tools-preview
          # - uses: Swatinem/rust-cache@v2 # v2

          - name: Install latest nextest release
            uses: taiki-e/install-action@v2 # v2
            with:
                tool: nextest
          - name: Install cargo-llvm-cov
            uses: taiki-e/install-action@v2 # v2
            with:
              tool: cargo-llvm-cov
          - name: install package
            run: |
                sudo apt-get update
                sudo apt-get install fuse3 libfuse3-dev

          # - name: test-run
          #   run: |
          #       mkdir sourcedata
          #       mkdir testdata
          #       touch sourcedata/testfile
          #       cargo build
          #       ./target/debug/rfuses_device_local link ./sourcedata ./testdata/ -v

          - name: Collect coverage data
            # Generate separate reports for nextest and doctests, and combine them.
            run: |
                cargo llvm-cov --no-report nextest --bound=all
                # cargo llvm-cov --no-report --doc
                cargo llvm-cov report --lcov --output-path lcov.info

          - name: Coveralls GitHub Action
            uses: coverallsapp/github-action@v2.3.0
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                files: lcov.info
